apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: cloudflare-api-token
  namespace: external-dns
spec:
  itemPath: "vaults/Kubernetes/items/cloudflare-api-token"