apiVersion: v1
kind: Namespace
metadata:
  name: loki
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: minio-secrets
  namespace: loki
spec:
  itemPath: vaults/Kubernetes/items/minio-secrets
